=== Sandy4321/myriad-toolkit/tools/skeleton/task/initialize/project/specification/specification.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dima.tu-berlin.de/myriad/specification" xmlns:myriad="http://www.dima.tu-berlin.de/myriad/specification" elementFormDefault="qualified">

  <!-- permitted root elements -->

  <xs:element name="generator_specification" type="myriad:generator_specification" />

  <!-- model-specification root type -->

  <xs:complexType name="generator_specification">
    <xs:sequence>
      <xs:element name="parameters" type="parameters_conatiner">
        <xs:annotation>
          <xs:documentation>A list of global generator parameters.</xs:documentation>
        </xs:annotation>
        <xs:unique name="parameter_name">
          <xs:selector xpath=".//myriad:parameter" />
          <xs:field xpath="@name"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="functions" type="myriad:functions">
        <xs:annotation>
          <xs:documentation>A list of named probability functions.</xs:documentation>
        </xs:annotation>
        <xs:unique name="function_name">
          <xs:selector xpath=".//myriad:function" />
          <xs:field xpath="@name"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="string_sets" type="myriad:string_sets">
        <xs:annotation>
          <xs:documentation>Finite string sets used in the described domain model.</xs:documentation>
        </xs:annotation>
        <xs:key name="string_set_name">
          <xs:selector xpath=".//myriad:string-set" />
          <xs:field xpath="@name" />
        </xs:key>
      </xs:element>
      <xs:element name="enumerations" type="myriad:enumerations">
        <xs:annotation>
          <xs:documentation>Enumertions used in the described domain model.</xs:documentation>
        </xs:annotation>
        <xs:key name="enumeration_name">
          <xs:selector xpath=".//myriad:enumeration" />
          <xs:field xpath="@name" />
        </xs:key>
      </xs:element>
      <xs:element name="record_sequences" type="myriad:record_sequences">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- parameters and arguments -->

  <!-- parameters -->
  <xs:group name="parameters">
    <xs:sequence>
      <xs:element name="parameter" type="myriad:parameter" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="parameters_conatiner">
    <xs:group ref="parameters" />
  </xs:complexType>
  <xs:complexType name="parameter">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:NCName" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <!-- arguments -->
  <xs:group name="arguments">
    <xs:sequence>
      <xs:element name="argument" type="myriad:argument" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="arguments_conatiner">
    <xs:group ref="parameters" />
  </xs:complexType>
  <xsd:complexType name="argument" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="parameter" type="parameter" />
    </xsd:choice>
    <xsd:attribute name="type" type="parameter_type" />
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="key" type="xsd:string" />
    <xsd:attribute name="on-invalid" type="invalid_sequence" />
  </xsd:complexType>

  <!-- functions -->

  <xs:complexType name="functions">
    <xs:sequence>
      <xs:element name="function" type="myriad:function" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- function -->
  <xs:complexType name="function">
    <xs:choice>
      <xs:element name="argument" type="myriad:argument" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="probability" type="myriad:probability-point-inline" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:Name" use="required" />
  </xs:complexType>
  <!-- probability points for the custom discrete probability type -->
  <xs:complexType name="probability-point-inline">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="argument" type="xs:int" use="required" />
        <xs:attribute name="value" type="xs:double" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- in-condext defined probability points -->
  <xs:complexType name="probability-point-context">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="function" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:double" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- partitioning configs -->
  <xs:complexType name="partitioners">
    <xs:sequence>
      <xs:element name="partitioner" type="myriad:partitioner" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- base partition type -->
  <xs:complexType name="partitioner">
    <xs:group ref="myriad:parameters" />
    <xs:attribute name="sequence" type="xs:NCName" use="required" />
    <xs:attribute name="type" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- string-sets -->

  <xs:complexType name="string_sets">
    <xs:sequence>
      <xs:element name="string_set" type="myriad:string_set" minOccurs="0" maxOccurs="unbounded">
        <xs:key name="string_set_item_value">
          <xs:selector xpath=".//myriad:item" />
          <xs:field xpath="@value" />
        </xs:key>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="string_set">
    <xs:sequence>
      <xs:element name="item" type="myriad:item" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- enumerations -->

  <xs:complexType name="enumerations">
    <xs:sequence>
      <xs:element name="enumeration" type="myriad:enumeration" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="enumeration">
    <xs:sequence>
      <xs:element name="item" type="myriad:item" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- set and enumeration items -->

  <xs:complexType name="item">
    <xs:sequence>
      <xs:element name="probability" type="myriad:probability-point-context" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <!-- record sequences -->

  <xs:complexType name="record_sequences">
    <xs:sequence>
      <xs:element name="random_sequence" type="myriad:random_sequence" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="random_sequence">
    <xs:sequence>
      <xs:element name="record_type" type="myriad:record_type" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="hydrators" type="myriad:hydrators" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="hydrator_chain" type="myriad:hydrator_chain" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="generator_tasks" type="myriad:generator_tasks" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:NCName" use="required" />
    <xs:attribute name="base_cardinality" type="parameter_reference" use="required" />
  </xs:complexType>
  <xs:complexType name="record_type">
    <xs:sequence>
      <xs:element name="field" type="myriad:field_type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="field_type">
    <xs:attribute name="name" type="xs:NCName" />
    <xs:attribute name="type" type="xs:NCName" />
  </xs:complexType>
  <xs:complexType name="hydrators">
    <xs:sequence>
      <xs:element name="hydrator" type="myriad:hydrator" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="hydrator">
    <xs:group ref="myriad:parameters" />
    <xs:attribute name="name" type="xs:NCName" />
    <xs:attribute name="type" type="xs:NCName" />
  </xs:complexType>
  <xs:complexType name="hydrator_chain">
  </xs:complexType>
  <xs:complexType name="generator_tasks">
    <xs:sequence>
      <xs:element name="generator_task" type="myriad:generator_task" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="generator_task">
  </xs:complexType>



  <!-- OLD <xs:complexType name="record-type-type"> <xs:sequence> <xs:element name="fields"> <xs:complexType> <xs:sequence> <xs:element name="field" type="myriad:field-type" maxOccurs="64" /> </xs:sequence> </xs:complexType> </xs:element> <xs:element name="hydrator-chain"> <xs:complexType> <xs:sequence> 
    <xs:element name="hydrator" type="myriad:hydrator-type" maxOccurs="128" /> </xs:sequence> </xs:complexType> </xs:element> </xs:sequence> <xs:attribute name="name" type="xs:NCName" use="required" /> </xs:complexType> <!- - field type - -> <xs:complexType name="field-type"> <xs:attribute name="name" type="xs:NCName" 
    use="required" /> <xs:attribute name="type" type="xs:string" use="required" /> <xs:attribute name="references" type="xs:string" /> </xs:complexType> <!- - hydrator types - -> <xs:complexType name="hydrator-type" abstract="true"> <xs:attribute name="field" type="xs:NCName" use="required" /> </xs:complexType> 
    <xs:complexType name="const-hydrator"> <xs:complexContent> <xs:extension base="myriad:hydrator-type"> <xs:attribute name="value" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="clustered-sequence-hydrator"> <xs:complexContent> <xs:extension base="myriad:hydrator-type"> 
    <xs:attribute name="interval-field" type="xs:NCName" /> <xs:attribute name="cardinality" type="xs:string" /> <xs:attribute name="probability" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="clustered-reference-hydrator"> <xs:complexContent> <xs:extension 
    base="myriad:hydrator-type"> <xs:attribute name="cluster-interval-field" type="xs:NCName" /> <xs:attribute name="probability" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="randomized-sequence-hydrator"> <xs:complexContent> <xs:extension base="myriad:hydrator-type"> 
    <xs:attribute name="cardinality" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="enum-set-hydrator"> <xs:complexContent> <xs:extension base="myriad:hydrator-type"> <xs:attribute name="probability" type="xs:string" /> </xs:extension> </xs:complexContent> 
    </xs:complexType> <xs:complexType name="static-set-hydrator"> <xs:complexContent> <xs:extension base="myriad:hydrator-type"> <xs:attribute name="set" type="xs:string" /> <xs:attribute name="probability" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="repeated-hydrator"> 
    <xs:complexContent> <xs:extension base="myriad:hydrator-type"> <xs:sequence> <xs:element name="hydrator" type="myriad:hydrator-type" /> </xs:sequence> <xs:attribute name="count-field" type="xs:NCName" /> </xs:extension> </xs:complexContent> </xs:complexType> <xs:complexType name="conditional-hydrator"> 
    <xs:complexContent> <xs:extension base="myriad:hydrator-type"> <xs:sequence> <xs:element name="if" maxOccurs="64"> <xs:complexType> <xs:sequence> <xs:element name="hydrator" type="myriad:hydrator-type" /> </xs:sequence> <xs:attribute name="cond-value" type="xs:string" use="required" /> </xs:complexType> 
    </xs:element> </xs:sequence> <xs:attribute name="cond-field" type="xs:string" /> </xs:extension> </xs:complexContent> </xs:complexType> STUFF -->
</xs:schema>

=== Sandy4321/myriad-toolkit/tools/skeleton/task/initialize/project/specification/generator-specification.xml
<?xml version="1.0" encoding="utf-8"?>
<generator_specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dima.tu-berlin.de/myriad/specification" xsi:schemaLocation="http://www.dima.tu-berlin.de/myriad/specification specification.xsd">

  <!-- configurable properties -->
  <parameters>
    <!-- user properties -->
    <parameter key="user.output_file">user.json</parameter>
    <!-- user_connections properties -->
    <parameter key="user_connections.output_file">user_connections.json</parameter>
    <parameter key="user_connections.connections_cardinality">100</parameter>
    <parameter key="user_connections.cluster_size">200</parameter>
    <parameter key="user_connections.cluster_connections_factor">0.8</parameter>
  </parameters>

  <!-- function configuration -->
  <functions>
    <function key="Pr[male_name]" type="custom_discrete_probability" />
    <function key="Pr[female_name]" type="custom_discrete_probability" />
    <function key="Pr[surname]" type="custom_discrete_probability" />
    <function key="Pr[gender]" type="custom_discrete_probability" />
    <function key="Pr[uc:cluster_connection]" type="pareto_probability">
      <argument key="x_min">1</argument>
      <argument key="alpha">1</argument>
    </function>
  </functions>

  <!-- string sets -->
  <string_sets>
    <!-- us male firstnames -->
    <string_set key="male_names">
      <item value="James">
        <probability function="Pr[male_name]" value='0.0372726560947861000' />
      </item>
      <item value="John">
        <probability function="Pr[male_name]" value='0.0367004386998328000' />
      </item>
      <item value="Robert">
        <probability function="Pr[male_name]" value='0.0352642857944282000' />
      </item>
    </string_set>
  </string_sets>

  <!-- enumeration types -->
  <enumerations>
    <enumeration key="Gender">
      <item value="Male">
        <probability function="Pr[gender]" value='0.493' />
      </item>
      <item value="Female">
        <probability function="Pr[gender]" value='0.507' />
      </item>
    </enumeration>
  </enumerations>

  <record_sequences>
    <!-- users -->
    <random_sequence key="user" base_cardinality="%user_connections.sequence.base_cardinality%">
      <record_type>
        <field name="id" type="I64u" />
        <field name="gender" type="Gender" />
        <field name="first_name" type="String" />
        <field name="last_name" type="String" />
      </record_type>
      <hydrators>
        <hydrator key="id_hydrator" type="randomized_sequence_hydrator">
          <argument key="field" type="field_ref" ref="id" />
          <argument key="cardinality" type="long" value="%user.sequence.cardinality%" />
        </hydrator>
        <hydrator key="gender_hydrator" type="enum_set_hydrator">
          <argument key="field" type="field_ref" ref="id" />
          <argument key="probability" type="function_ref" ref="Pr[myriad:uniform]" />
        </hydrator>
        <hydrator key="first_name_hydrator" type="conditional_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="condition_field" type="field_ref" ref="gender" />
          <argument key="choices" type="map">
            <argument key="Male" type="hydrator_ref" ref="first_name_male_hydrator" />
            <argument key="Female" type="hydrator_ref" ref="first_name_female_hydrator" />
          </argument>
        </hydrator>
        <hydrator key="first_name_male_hydrator" type="static_set_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="set" type="set_ref" ref="male_names" />
          <argument key="probability" type="function_ref" ref="Pr[male_names]" />
        </hydrator>
        <hydrator key="first_name_female_hydrator" type="static_set_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="set" type="set_ref" ref="female_names" />
          <argument key="probability" type="function_ref" ref="Pr[female_names]" />
        </hydrator>
      </hydrators>
      <hydration_plan>
        <hydrator_ref ref="id_hydrator" />
        <hydrator_ref ref="gender_hydrator" />
        <hydrator_ref ref="first_name_hydrator" />
      </hydration_plan>
      <generator_tasks>
        <generator_task key="user.generate" type="partitioned_iterator" />
      </generator_tasks>
    </random_sequence>

    <!-- user connections -->
    <random_sequence key="user_connections" base_cardinality="750000">
      <record_type>
        <field name="id" type="I64u" />
        <field name="cluster_id" type="I64u" />
        <field name="cluster_interval" type="Interval" />
        <field name="connections_count" type="vector[I64u]" />
        <field name="connections" type="vector[I64u]" />
      </record_type>
      <hydrators>
        <hydrator key="id_hydrator" type="randomized_sequence_hydrator">
          <argument key="field" type="field_ref" ref="id" />
          <argument key="cardinality" type="long" value="%user_connections.sequence.cardinality%" />
        </hydrator>
        <hydrator key="connections_count_hydrator" type="const_hydrator">
          <argument key="field" type="field_ref" ref="connections_count" />
          <argument key="const_value" type="I64u" value="%user_connections.connections_count%" />
        </hydrator>
        <hydrator key="cluster_id_hydrator" type="clustered_sequence_hydrator">
          <argument key="field" type="field_ref" ref="cluster_id" />
          <argument key="interval_field" type="field_ref" ref="cluster_interval" />
          <argument key="const_value" type="I16u" value="%user_connections.connections_count%" />
          <argument key="cardinality" type="I16u" value="${%user_connections.sequence.cardinality% / %user_connections.cluster_size%}" />
          <argument key="probability" type="function_ref" ref="Pr[myriad:uniform]" />
        </hydrator>
        <hydrator key="connections_hydrator" type="repeated_hydrator">
          <argument key="field" type="field_ref" ref="connections" />
          <argument key="count_field" type="field_ref" ref="connections_count" />
          <argument key="inner_hydrator" type="hydrator_ref" />
        </hydrator>
        <hydrator key="connection_hydrator" type="clustered_reference_hydrator">
          <argument key="field" type="field_ref" ref="connections" />
          <argument key="restriction_interval_field" type="field_ref" ref="cluster_interval" />
          <argument key="probability" type="function_ref" ref="Pr[uc:cluster_connection]" />
        </hydrator>
      </hydrators>
      <hydration_plan>
        <hydrator_ref ref="id_hydrator" />
        <hydrator_ref ref="cluster_id_hydrator" />
        <hydrator_ref ref="connections_count_hydrator" />
        <hydrator_ref ref="connections_hydrator" />
      </hydration_plan>
      <generator_tasks>
      </generator_tasks>
    </random_sequence>
  </record_sequences>
</generator_specification>
